[package]
name = "libsql-experimental"
version = "0.0.1"
description = ""
authors = ["Pekka Enberg <penberg@iki.fi>"]
license = "MIT"
edition = "2021"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
libsql = { git = "https://github.com/libsql/libsql/", rev = "c2cf4380bbf254ec7bd2f10c025a260a123bdcb5" }

[dependencies.neon]
version = "0.10"
default-features = false
features = ["napi-6"]
