[package]
name = "libsql-experimental"
version = "0.0.1"
description = ""
authors = ["Pekka Enberg <penberg@iki.fi>"]
license = "MIT"
edition = "2021"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
libsql = { git = "https://github.com/libsql/libsql/", rev = "8c3263b1c13421955a67c5b650c2a21c275f4791" }
tokio = { version = "1.29.1", features = [ "rt-multi-thread" ] }

[dependencies.neon]
version = "0.10"
default-features = false
features = ["napi-6"]
