[package]
name = "libsql-js"
version = "0.2.0-pre.2"
description = ""
authors = ["Pekka Enberg <penberg@iki.fi>"]
license = "MIT"
edition = "2021"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
tracing-subscriber = "0.3"
libsql = { git = "https://github.com/libsql/libsql/", rev = "8045a458e72f8622c57730f3a7ba87ce8e40b255" }
tracing = "0.1"
once_cell = "1.18.0"
tokio = { version = "1.29.1", features = [ "rt-multi-thread" ] }

[dependencies.neon]
version = "1.0.0-alpha.4"
default-features = false
features = ["napi-6"]

[profile.release]
lto = true
codegen-units = 1
debug = false
strip = true
opt-level = "z"
panic = "abort"

