[package]
name = "libsql-experimental"
version = "0.0.1"
description = ""
authors = ["Pekka Enberg <penberg@iki.fi>"]
license = "MIT"
edition = "2021"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
libsql = { git = "https://github.com/libsql/libsql/", rev = "3e75012192fedaa8e2c7faa9f02610c1bae1cc07" }
tokio = { version = "1.29.1", features = [ "rt-multi-thread" ] }

[dependencies.neon]
version = "1.0.0-alpha.4"
default-features = false
features = ["napi-6"]

[patch.crates-io]
tonic = { git = "https://github.com/hyperium/tonic" }
tonic-web = { git = "https://github.com/hyperium/tonic" }
tower-http = { git = "https://github.com/tower-rs/tower-http", branch = "lucio/grpc-defaults" }
