[package]
name = "libsql-experimental"
version = "0.0.1"
description = ""
authors = ["Pekka Enberg <penberg@iki.fi>"]
license = "MIT"
edition = "2021"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
libsql = { git = "https://github.com/psarna/libsql/", rev = "f70da8bdeffaf8f21514018399577a97b7777da9", default-features = false }

[dependencies.neon]
version = "0.10"
default-features = false
features = ["napi-6"]
