[package]
name = "libsql-js"
version = "0.4.0-pre.6"
description = ""
authors = ["Pekka Enberg <penberg@iki.fi>"]
license = "MIT"
edition = "2021"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
libsql = { git = "https://github.com/tursodatabase/libsql/", rev = "8521f874f67365fc07f0469681f3351d65f3c761", features = ["encryption"] }
tracing = "0.1"
once_cell = "1.18.0"
tokio = { version = "1.29.1", features = [ "rt-multi-thread" ] }
neon = { version = "1.0.0", default-features = false, features = ["napi-6"] }

[profile.release]
lto = true
codegen-units = 1
debug = false
strip = true
panic = "abort"

