[package]
name = "libsql-js"
version = "0.0.1"
description = ""
authors = ["Pekka Enberg <penberg@iki.fi>"]
license = "MIT"
edition = "2021"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
env_logger = "0.10.0"
libsql = { git = "https://github.com/libsql/libsql/", rev = "7fd280beadc09a6aeb19bc601635297d6bbadf17" }
log = "0.4.20"
once_cell = "1.18.0"
tokio = { version = "1.29.1", features = [ "rt-multi-thread" ] }

[dependencies.neon]
version = "1.0.0-alpha.4"
default-features = false
features = ["napi-6"]
