[package]
name = "libsql-experimental"
version = "0.0.1"
description = ""
authors = ["Pekka Enberg <penberg@iki.fi>"]
license = "MIT"
edition = "2021"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
libsql = { git = "https://github.com/libsql/libsql/", rev = "af54ae9976dec3497fdbd23191c32b9ad6025a35" }

[dependencies.neon]
version = "0.10"
default-features = false
features = ["napi-6"]
