[package]
name = "libsql-experimental"
version = "0.0.1"
description = ""
authors = ["Pekka Enberg <penberg@iki.fi>"]
license = "MIT"
edition = "2021"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
libsql = { git = "https://github.com/libsql/libsql/", rev = "0b28b0b005a1122ae372f8f799589f1689c1c10b" }
tokio = { version = "1.29.1", features = [ "rt-multi-thread" ] }

[dependencies.neon]
version = "0.10"
default-features = false
features = ["napi-6"]

[patch.crates-io]
tonic = { git = "https://github.com/hyperium/tonic" }
tonic-web = { git = "https://github.com/hyperium/tonic", branch = "lucio/grpc-web-client" }
