name: CI

env:
  NODE_VERSION: 18.x
  NPM_REGISTRY: 'https://registry.npmjs.org'

on:
  push:
    # Prevent duplicate runs of this workflow on our own internal PRs.
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - main

jobs:
  pack:
    name: Pack (main)
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Pack
        uses: neon-actions/pack@v0.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          github-release: false

  macos-builds:
    name: Builds (macOS)
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]
    runs-on: macos-arm64
    permissions:
      contents: write
    steps:
      - name: Build
        uses: neon-actions/build@v0.1
        with:
          target: ${{ matrix.target }}
          node-version: ${{ env.NODE_VERSION }}
          npm-publish: false
          github-release: false

  windows-builds:
    name: Builds (Windows)
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-msvc]
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Build
        uses: neon-actions/build@v0.1
        with:
          target: ${{ matrix.target }}
          node-version: ${{ env.NODE_VERSION }}
          npm-publish: false
          github-release: false

  other-builds:
    name: Builds (other platforms)
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-gnu, x86_64-unknown-linux-musl]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Build
        uses: neon-actions/build@v0.1
        with:
          target: ${{ matrix.target }}
          node-version: ${{ env.NODE_VERSION }}
          use-cross: true
          npm-publish: false
          github-release: false
