name: CI

env:
  NODE_VERSION: 18.x
  NPM_REGISTRY: 'https://registry.npmjs.org'

on:
  push:
    # Prevent duplicate runs of this workflow on our own internal PRs.
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - main

jobs:
  macos-builds:
    name: Builds (macOS)
    strategy:
      fail-fast: false
      matrix:
        platform: [darwin-x64, darwin-arm64]
    runs-on: macos-arm64
    permissions:
      contents: write
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: env.NODE_VERSION
      - name: Install Dependencies
        shell: bash
        run: npm ci --verbose
      - name: Build
        uses: neon-actions/build@v0.9
        with:
          platform: ${{ matrix.platform }}
          node-version: ${{ env.NODE_VERSION }}
          npm-publish: false
          github-release: false

  windows-builds:
    name: Builds (Windows)
    strategy:
      fail-fast: false
      matrix:
        platform: [win32-x64-msvc]
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: env.NODE_VERSION
      - name: Install Dependencies
        shell: bash
        run: npm ci --verbose
      - name: Build
        uses: neon-actions/build@v0.9
        with:
          platform: ${{ matrix.platform }}
          node-version: ${{ env.NODE_VERSION }}
          npm-publish: false
          github-release: false

  other-builds:
    name: Builds (other platforms)
    strategy:
      fail-fast: false
      matrix:
        platform: [linux-x64-gnu, linux-x64-musl, linux-arm64-gnu, linux-arm64-musl]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: env.NODE_VERSION
      - name: Install Dependencies
        shell: bash
        run: npm ci --verbose
      - name: Build
        uses: neon-actions/build@v0.9
        with:
          platform: ${{ matrix.platform }}
          node-version: ${{ env.NODE_VERSION }}
          use-cross: true
          npm-publish: false
          github-release: false
